config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/venues')
  resources :homes
  resources :venues
  resources :types
  resources :info
  resources :results
  resources :images
  resources :firsts
  resources :kibos

  get '/info', to: 'info#index'
  get '/types/:id/select', to: 'types#select', as: 'select'
  get '/images/:id/select', to: 'images#select', as: 'image_select'
  get '/kibos/:id/select', to: 'kibos#select', as: 'kibo_select'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diy.rb
class Diy < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  belongs_to :venue
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :venue
end

app/models/type.rb
class Type < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :invoices
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :venue_genre
  has_many :reviews
  has_many :invoices
  has_many :venue_images
end

app/models/venue_genre.rb
class VenueGenre < ApplicationRecord
  has_many :venues
end

app/models/venue_image.rb
class VenueImage < ApplicationRecord
  belongs_to :venue

  def image_url
    "http://www.mwed.jp/d#{path}"
  end
end

app/controllers/firsts_controller.rb
class FirstsController < ApplicationController
	def index
	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	def index
		@images = Venue.all.pluck(:image_type).uniq
	end

	def show
		@venue = Venue.find(params[:id])
	end

	def select
		cookies[:selected_venue_id] = params[:id]
		redirect_to venues_path
	end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
    table_names = ApplicationRecord.connection.tables
    @model_names = table_names.each_with_object([]) { |table_name, arr| arr << table_name.singularize }
  end
end

app/controllers/kibos_controller.rb
class KibosController < ApplicationController
	def select
		cookies[:selected_kibo] = params[:id]
		redirect_to venues_path
	end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController

	def index
	end

	def show
		@venue = Venue.find(params[:id])

    	p cookies[:selected_venue_id]
	end

	def select
		cookies[:selected_venue_id] = params[:id]
		redirect_to venues_path
	end

	def result
		@venue = Venue.new(params[:id])
		redirect_to @result
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/kibo_helper.rb
module KiboHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/images/index.html.erb
<% @images.each do |image| %>
	<h3>
		・<%= image %>
	</h3>
	<div class="image">
	<% Venue.where(image_type: image).limit(3).each do |venue| %>
		<%= link_to image_path(venue.id) do %>
			<%= image_tag(venue.venue_images.third.image_url, size: '100x100') %>
		<% end %>
	<% end %>
	</div><br>
<% end %>

app/views/images/show.html.erb
<h3><%= @venue.name %></h3>
<%= image_tag(@venue.venue_images.third.image_url, :class => "imagesize") %>
<p>この画像でいいですか？</p>
<div>
<button type="button" class="btn btn-success"><%= link_to "はい", select_path(id: @venue.id) %></button>
<button type="button" class="btn btn-success"><%= link_to "いいえ", images_path %></button>
</div>

app/views/kibos/index.html.erb
<div class="image">
<h3>・身内のみ（~20人）</h3>
	<%= link_to kibo_select_path('shokibo') do %>
		<%= image_tag("miuchi.png", :size => "250x150") %>
	<% end %>
<br><h3>・友人・職場の人も(~70人)</h3>
	<%= link_to kibo_select_path('tyukibo') do %>
		<%= image_tag("sokosoko.jpg", :size => "250x150") %>
	<% end %>
<br><h3>・大人数(70人~)</h3>
	<%= link_to kibo_select_path('daikibo') do %>
		<%= image_tag("daitasuu.jpg", :size => "250x150") %>
	<% end %>
</div>

app/views/types/index.html.erb
<% VenueGenre.all.each do |genre| %>
	<h3>
	・<%= genre.name %>
	</h3>
	<div class="image">
		<% genre.venues.limit(3).each do |venue| %>
			<%= link_to type_path(venue.id) do %>
				<%= image_tag(venue.venue_images.second.image_url, :size => "100x100") %>
			<% end %>
		<% end %>
	</div>
<% end %>

app/views/types/show.html.erb
<h3><%= @venue.name %></h3>
<%= image_tag(@venue.venue_images.second.image_url, :class => "imagesize") %>
<p>この画像でいいですか？</p>
<div>
<button type="button" class="btn btn-success"><%= link_to "はい", select_path(id: @venue.id) %></button>
<button type="button" class="btn btn-success"><%= link_to "いいえ", types_path %></button>
</div>